name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 18 * * *
  watch:
    types: started

env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}
  UPLOAD_BESULT_DIR: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Run install
        run: npm install

      - name: Run Script
        run: node Start.js
        timeout-minutes: 60

      - name: Upload result file
        uses: actions/upload-artifact@master
        if: env.UPLOAD_BESULT_DIR == 'true'
        with:
          name: result
          path: ./*.txt

